apiVersion: v1
kind: ConfigMap
metadata:
  name: AllKnow-config
  namespace: AllKnow
data:
  ENVIRONMENT: "production"
  CLOUD_PROVIDER: "aws"
  VECTOR_STORE_TYPE: "pinecone"
  PINECONE_CLOUD: "aws"
  PINECONE_REGION: "us-east-1"
  S3_BUCKET_NAME: "AllKnow-uploads"
  S3_REGION: "us-east-1"
  EMBEDDING_MODEL: "sentence-transformers/all-mpnet-base-v2"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  CORS_ORIGINS: '["*"]'